// Auto-generated by crawler (npm run export:local). Do not edit by hand.
window.WAI_PARKING_DATA = {
  "__generatedAt": "2026-09-22T06:45:09.929Z",
  "taitungCounty": [
    {
      "name": "中央市場停車場",
      "lat": 22.7528341,
      "lng": 121.1491719,
      "address": "台東市信義路187-179號",
      "phone": "089-342500",
      "smallSpots": 28,
      "motoSpots": 45,
      "source": "taitung_gov_parking"
    },
    {
      "name": "停五公有停車場",
      "lat": 22.7552484,
      "lng": 121.1448522,
      "address": "台東市新生路191號",
      "phone": "089-225228",
      "smallSpots": 73,
      "source": "taitung_gov_parking"
    },
    {
      "name": "光明路停車場(月租)",
      "lat": 22.7527036,
      "lng": 121.1491123,
      "address": "台東市光明路264號",
      "phone": "0929-129888",
      "smallSpots": 9,
      "source": "taitung_gov_parking"
    },
    {
      "name": "加路蘭遊憩區停車場",
      "lat": 22.8063665,
      "lng": 121.1969974,
      "address": "台東市台11線",
      "phone": "089-280313",
      "largeSpots": 4,
      "smallSpots": 28,
      "motoSpots": 20,
      "source": "taitung_gov_parking"
    },
    {
      "name": "叭叭房台東開封停車場(供宿客)",
      "lat": 22.7594531,
      "lng": 121.1381503,
      "address": "台東市開封街696號",
      "phone": "02-2528-2826",
      "smallSpots": 11,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東停一停車場",
      "lat": 22.7920847,
      "lng": 121.1227377,
      "address": "台東市岩灣路101巷610號後方",
      "phone": "089-226506",
      "smallSpots": 285,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東停二停車場",
      "lat": 22.7945812,
      "lng": 121.1232102,
      "address": "台東市岩灣路101巷439號右方",
      "phone": "089-226506",
      "smallSpots": 203,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東市新生地下停車場",
      "lat": 22.7521461,
      "lng": 121.1475914,
      "address": "台東市新生路93-97號",
      "phone": "089-357718",
      "evSpots": 1,
      "smallSpots": 332,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東森林公園第一停車場",
      "lat": 22.7634187,
      "lng": 121.1588754,
      "address": "台東市華泰路300號",
      "phone": "089-362025",
      "smallSpots": 105,
      "motoSpots": 74,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(A區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "smallSpots": 112,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(B區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "evSpots": 1,
      "smallSpots": 120,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(C區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "motoSpots": 630,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(D區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "smallSpots": 89,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東航空站停車場",
      "lat": 22.761315,
      "lng": 121.1439117,
      "address": "台東市民航路1100號",
      "phone": "089-361111",
      "evSpots": 4,
      "smallSpots": 209,
      "source": "taitung_gov_parking"
    },
    {
      "name": "國立臺東大學產學創新園區停車場",
      "lat": 22.7505589,
      "lng": 121.1472319,
      "address": "台東市中華路一段684號",
      "phone": "089-352305",
      "largeSpots": 6,
      "smallSpots": 83,
      "source": "taitung_gov_parking"
    },
    {
      "name": "城市商旅台東鄭州停車場(供宿客)",
      "lat": 22.7618543,
      "lng": 121.1445746,
      "address": "台東市鄭州街13號",
      "phone": "080 020 8333",
      "smallSpots": 86,
      "source": "taitung_gov_parking"
    },
    {
      "name": "基督教醫院停車場",
      "lat": 22.7637889,
      "lng": 121.1461593,
      "address": "台東市開封街350號",
      "phone": "089-323362",
      "smallSpots": 107,
      "source": "taitung_gov_parking"
    },
    {
      "name": "大同路停車場",
      "lat": 22.7534986,
      "lng": 121.1531208,
      "address": "台東市大同路停車場福建路路口",
      "phone": "089-351999",
      "smallSpots": 33,
      "source": "taitung_gov_parking"
    },
    {
      "name": "富岡地質公園停車場",
      "lat": 22.7943653,
      "lng": 121.1954612,
      "address": "台東市松江路一段500號",
      "phone": "089-281530",
      "largeSpots": 27,
      "smallSpots": 93,
      "motoSpots": 49,
      "source": "taitung_gov_parking"
    },
    {
      "name": "富綠汽車停車場(供遊客)",
      "lat": 22.7929705,
      "lng": 121.1894423,
      "address": "台東市富岡街175號",
      "phone": "0920-054862",
      "smallSpots": 8,
      "source": "taitung_gov_parking"
    },
    {
      "name": "成功鎮三民里第二市場停車場(月租)",
      "lat": 23.1041567,
      "lng": 121.3746756,
      "address": "台東縣成功鎮三民里三民路111號",
      "phone": "089-851004",
      "smallSpots": 8,
      "source": "taitung_gov_parking"
    },
    {
      "name": "旗魚飯店停車場(供宿客)",
      "lat": 22.7506328,
      "lng": 121.1503437,
      "address": "台東市新生路49號",
      "phone": "089-336360",
      "smallSpots": 31,
      "source": "taitung_gov_parking"
    },
    {
      "name": "東大同停車場",
      "lat": 22.75453,
      "lng": 121.1528793,
      "address": "台東市中華路一段376巷7號",
      "phone": "089-321313",
      "smallSpots": 20,
      "source": "taitung_gov_parking"
    },
    {
      "name": "波浪屋停車場",
      "lat": 22.7534225,
      "lng": 121.1472995,
      "address": "台東市新生路170號",
      "phone": "089-342500",
      "smallSpots": 29,
      "source": "taitung_gov_parking"
    },
    {
      "name": "知本國家森林遊樂區停車場",
      "lat": 22.686961,
      "lng": 120.99214,
      "address": "台東縣卑南鄉龍泉路290號",
      "phone": "089-510961#10",
      "smallSpots": 75,
      "source": "taitung_gov_parking"
    },
    {
      "name": "衛生福利部台東醫院停車場",
      "lat": 22.7574517,
      "lng": 121.1508134,
      "address": "台東市五權街1號",
      "phone": "089-324112",
      "smallSpots": 23,
      "source": "taitung_gov_parking"
    },
    {
      "name": "豐榮路停車場(月租型)",
      "lat": 22.7477286,
      "lng": 121.1356096,
      "address": "台東市豐 榮路145巷",
      "phone": "089-351999",
      "smallSpots": 46,
      "source": "taitung_gov_parking"
    },
    {
      "name": "長濱鄉一號停車場(月租)",
      "lat": 23.3180619,
      "lng": 121.4484747,
      "address": "臺東縣長濱鄉長濱村7鄰中興23號",
      "phone": "089-832139",
      "smallSpots": 59,
      "source": "taitung_gov_parking"
    },
    {
      "name": "阿華停車場(供遊客)",
      "lat": 22.7970484,
      "lng": 121.1874228,
      "address": "台東市富岡里松江路一段101巷139之1號",
      "phone": "0905-100530",
      "smallSpots": 16,
      "source": "taitung_gov_parking"
    },
    {
      "name": "馬偕醫院停車場",
      "lat": 22.7511505,
      "lng": 121.1406099,
      "address": "台東市長沙街303巷1號",
      "phone": "089-310150",
      "smallSpots": 79,
      "source": "taitung_gov_parking"
    }
  ]
};
